import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    FETCH_PRODUCT_LIST: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST`,
    FETCH_PRODUCT_LIST_REQUEST: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST_REQUEST`,
    FETCH_PRODUCT_LIST_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST_SUCCESS`,
    FETCH_PRODUCT_LIST_FAILURE: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST_FAILURE`,

    BUY_NOW: `${STATE_REDUCER_KEY}/BUY_NOW`,
    BUY_NOW_REQUEST: `${STATE_REDUCER_KEY}/BUY_NOW_REQUEST`,
    BUY_NOW_SUCCESS: `${STATE_REDUCER_KEY}/BUY_NOW_SUCCESS`,
    BUY_NOW_FAILURE: `${STATE_REDUCER_KEY}/BUY_NOW_FAILURE`,

    LOGIN: `${STATE_REDUCER_KEY}/LOGIN`,
    LOGIN_REQUEST: `${STATE_REDUCER_KEY}/LOGIN_REQUEST`,
    LOGIN_SUCCESS: `${STATE_REDUCER_KEY}/LOGIN_SUCCESS`,
    LOGIN_FAILURE: `${STATE_REDUCER_KEY}/LOGIN_FAILURE`
};
