import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    USER_PROFILE: `${STATE_REDUCER_KEY}/USER_PROFILE`,
    USER_PROFILE_REQUEST: `${STATE_REDUCER_KEY}/USER_PROFILE_REQUEST`,
    USER_PROFILE_SUCCESS: `${STATE_REDUCER_KEY}/USER_PROFILE_SUCCESS`,
    USER_PROFILE_FAILURE: `${STATE_REDUCER_KEY}/USER_PROFILE_FAILURE`,

    REGISTER: `${STATE_REDUCER_KEY}/REGISTER`,
    REGISTER_REQUEST: `${STATE_REDUCER_KEY}/REGISTER_REQUEST`,
    REGISTER_SUCCESS: `${STATE_REDUCER_KEY}/REGISTER_SUCCESS`,
    REGISTER_FAILURE: `${STATE_REDUCER_KEY}/REGISTER_FAILURE`,

    LOGIN: `${STATE_REDUCER_KEY}/LOGIN`,
    LOGIN_REQUEST: `${STATE_REDUCER_KEY}/LOGIN_REQUEST`,
    LOGIN_SUCCESS: `${STATE_REDUCER_KEY}/LOGIN_SUCCESS`,
    LOGIN_FAILURE: `${STATE_REDUCER_KEY}/LOGIN_FAILURE`
};

