import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    FETCH_ORDERS: `${STATE_REDUCER_KEY}/FETCH_ORDERS`,
    FETCH_ORDERS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_ORDERS_REQUEST`,
    FETCH_ORDERS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_ORDERS_SUCCESS`,
    FETCH_ORDERS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_ORDERS_FAILURE`,

    REGISTER: `${STATE_REDUCER_KEY}/REGISTER`,
    REGISTER_REQUEST: `${STATE_REDUCER_KEY}/REGISTER_REQUEST`,
    REGISTER_SUCCESS: `${STATE_REDUCER_KEY}/REGISTER_SUCCESS`,
    REGISTER_FAILURE: `${STATE_REDUCER_KEY}/REGISTER_FAILURE`,

    LOGIN: `${STATE_REDUCER_KEY}/LOGIN`,
    LOGIN_REQUEST: `${STATE_REDUCER_KEY}/LOGIN_REQUEST`,
    LOGIN_SUCCESS: `${STATE_REDUCER_KEY}/LOGIN_SUCCESS`,
    LOGIN_FAILURE: `${STATE_REDUCER_KEY}/LOGIN_FAILURE`
};

