import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    FETCH_ORDERS: `${STATE_REDUCER_KEY}/FETCH_ORDERS`,
    FETCH_ORDERS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_ORDERS_REQUEST`,
    FETCH_ORDERS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_ORDERS_SUCCESS`,
    FETCH_ORDERS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_ORDERS_FAILURE`
};

