import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    FETCH_PRODUCT_LIST: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST`,
    FETCH_PRODUCT_LIST_REQUEST: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST_REQUEST`,
    FETCH_PRODUCT_LIST_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST_SUCCESS`,
    FETCH_PRODUCT_LIST_FAILURE: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST_FAILURE`,

    CREATE_PRODUCT: `${STATE_REDUCER_KEY}/CREATE_PRODUCT`,
    CREATE_PRODUCT_REQUEST: `${STATE_REDUCER_KEY}/CREATE_PRODUCT_REQUEST`,
    CREATE_PRODUCT_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_PRODUCT_SUCCESS`,
    CREATE_PRODUCT_FAILURE: `${STATE_REDUCER_KEY}/CREATE_PRODUCT_FAILURE`,

    EDIT_PRODUCT: `${STATE_REDUCER_KEY}/EDIT_PRODUCT`,
    EDIT_PRODUCT_REQUEST: `${STATE_REDUCER_KEY}/EDIT_PRODUCT_REQUEST`,
    EDIT_PRODUCT_SUCCESS: `${STATE_REDUCER_KEY}/EDIT_PRODUCT_SUCCESS`,
    EDIT_PRODUCT_FAILURE: `${STATE_REDUCER_KEY}/EDIT_PRODUCT_FAILURE`,


    FETCH_PRODUCT_BY_ID: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_BY_ID`,
    FETCH_PRODUCT_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_BY_ID_REQUEST`,
    FETCH_PRODUCT_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_BY_ID_SUCCESS`,
    FETCH_PRODUCT_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_BY_ID_FAILURE`,

    DELETE_PRODUCT_BY_ID: `${STATE_REDUCER_KEY}/DELETE_PRODUCT_BY_ID`,
    DELETE_PRODUCT_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/DELETE_PRODUCT_BY_ID_REQUEST`,
    DELETE_PRODUCT_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/DELETE_PRODUCT_BY_ID_SUCCESS`,
    DELETE_PRODUCT_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/DELETE_PRODUCT_BY_ID_FAILURE`,

    CREATE_DUMMY_PROD: `${STATE_REDUCER_KEY}/CREATE_DUMMY_PROD`,
    CREATE_DUMMY_PROD_REQUEST: `${STATE_REDUCER_KEY}/CREATE_DUMMY_PROD_REQUEST`,
    CREATE_DUMMY_PROD_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_DUMMY_PROD_SUCCESS`,
    CREATE_DUMMY_PROD_FAILURE: `${STATE_REDUCER_KEY}/CREATE_DUMMY_PROD_FAILURE`,

    PRODUCT_IMAGE_UPLOAD: `${STATE_REDUCER_KEY}/PRODUCT_IMAGE_UPLOAD`,
    PRODUCT_IMAGE_UPLOAD_REQUEST: `${STATE_REDUCER_KEY}/PRODUCT_IMAGE_UPLOAD_REQUEST`,
    PRODUCT_IMAGE_UPLOAD_SUCCESS: `${STATE_REDUCER_KEY}/PRODUCT_IMAGE_UPLOAD_SUCCESS`,
    PRODUCT_IMAGE_UPLOAD_FAILURE: `${STATE_REDUCER_KEY}/PRODUCT_IMAGE_UPLOAD_FAILURE`,

    NEW_PRODUCT_IMAGE_UPLOAD: `${STATE_REDUCER_KEY}/NEW_PRODUCT_IMAGE_UPLOAD`,
    NEW_PRODUCT_IMAGE_UPLOAD_REQUEST: `${STATE_REDUCER_KEY}/NEW_PRODUCT_IMAGE_UPLOAD_REQUEST`,
    NEW_PRODUCT_IMAGE_UPLOAD_SUCCESS: `${STATE_REDUCER_KEY}/NEW_PRODUCT_IMAGE_UPLOAD_SUCCESS`,
    NEW_PRODUCT_IMAGE_UPLOAD_FAILURE: `${STATE_REDUCER_KEY}/NEW_PRODUCT_IMAGE_UPLOAD_FAILURE`,

    FETCH_ORDERS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_ORDERS_REQUEST`,
    FETCH_ORDERS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_ORDERS_SUCCESS`,
    FETCH_ORDERS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_ORDERS_FAILURE`,

    DASHBOARD_STATS_REQUEST: `${STATE_REDUCER_KEY}/DASHBOARD_STATS_REQUEST`,
    DASHBOARD_STATS_SUCCESS: `${STATE_REDUCER_KEY}/DASHBOARD_STATS_SUCCESS`,
    DASHBOARD_STATS_FAILURE: `${STATE_REDUCER_KEY}/DASHBOARD_STATS_FAILURE`,

    USERS_LIST_REQUEST: `${STATE_REDUCER_KEY}/USERS_LIST_REQUEST`,
    USERS_LIST_SUCCESS: `${STATE_REDUCER_KEY}/USERS_LIST_SUCCESS`,
    USERS_LIST_FAILURE: `${STATE_REDUCER_KEY}/USERS_LIST_FAILURE`,

    APPROVE_STUDENT_REQUEST: `${STATE_REDUCER_KEY}/APPROVE_STUDENT_REQUEST`,
    APPROVE_STUDENT_SUCCESS: `${STATE_REDUCER_KEY}/APPROVE_STUDENT_SUCCESS`,
    APPROVE_STUDENT_FAILURE: `${STATE_REDUCER_KEY}/APPROVE_STUDENT_FAILURE`,

    REJECT_STUDENT_REQUEST: `${STATE_REDUCER_KEY}/REJECT_STUDENT_REQUEST`,
    REJECT_STUDENT_SUCCESS: `${STATE_REDUCER_KEY}/REJECT_STUDENT_SUCCESS`,
    REJECT_STUDENT_FAILURE: `${STATE_REDUCER_KEY}/REJECT_STUDENT_FAILURE`,

    BLOCK_STUDENT_REQUEST: `${STATE_REDUCER_KEY}/BLOCK_STUDENT_REQUEST`,
    BLOCK_STUDENT_SUCCESS: `${STATE_REDUCER_KEY}/BLOCK_STUDENT_SUCCESS`,
    BLOCK_STUDENT_FAILURE: `${STATE_REDUCER_KEY}/BLOCK_STUDENT_FAILURE`,

    UN_BLOCK_STUDENT_REQUEST: `${STATE_REDUCER_KEY}/UN_BLOCK_STUDENT_REQUEST`,
    UN_BLOCK_STUDENT_SUCCESS: `${STATE_REDUCER_KEY}/UN_BLOCK_STUDENT_SUCCESS`,
    UN_BLOCK_STUDENT_FAILURE: `${STATE_REDUCER_KEY}/UN_BLOCK_STUDENT_FAILURE`,

    DELETE_PROFILE_REQUEST: `${STATE_REDUCER_KEY}/DELETE_PROFILE_REQUEST`,
    DELETE_PROFILE_SUCCESS: `${STATE_REDUCER_KEY}/DELETE_PROFILE_SUCCESS`,
    DELETE_PROFILE_FAILURE: `${STATE_REDUCER_KEY}/DELETE_PROFILE_FAILURE`


};
