import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    FETCH_PRODUCT_LIST: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST`,
    FETCH_PRODUCT_LIST_REQUEST: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST_REQUEST`,
    FETCH_PRODUCT_LIST_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST_SUCCESS`,
    FETCH_PRODUCT_LIST_FAILURE: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_LIST_FAILURE`,

    CREATE_PRODUCT: `${STATE_REDUCER_KEY}/CREATE_PRODUCT`,
    CREATE_PRODUCT_REQUEST: `${STATE_REDUCER_KEY}/CREATE_PRODUCT_REQUEST`,
    CREATE_PRODUCT_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_PRODUCT_SUCCESS`,
    CREATE_PRODUCT_FAILURE: `${STATE_REDUCER_KEY}/CREATE_PRODUCT_FAILURE`,

    EDIT_PRODUCT: `${STATE_REDUCER_KEY}/EDIT_PRODUCT`,
    EDIT_PRODUCT_REQUEST: `${STATE_REDUCER_KEY}/EDIT_PRODUCT_REQUEST`,
    EDIT_PRODUCT_SUCCESS: `${STATE_REDUCER_KEY}/EDIT_PRODUCT_SUCCESS`,
    EDIT_PRODUCT_FAILURE: `${STATE_REDUCER_KEY}/EDIT_PRODUCT_FAILURE`,


    FETCH_PRODUCT_BY_ID: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_BY_ID`,
    FETCH_PRODUCT_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_BY_ID_REQUEST`,
    FETCH_PRODUCT_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_BY_ID_SUCCESS`,
    FETCH_PRODUCT_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_PRODUCT_BY_ID_FAILURE`,

    DELETE_PRODUCT_BY_ID: `${STATE_REDUCER_KEY}/DELETE_PRODUCT_BY_ID`,
    DELETE_PRODUCT_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/DELETE_PRODUCT_BY_ID_REQUEST`,
    DELETE_PRODUCT_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/DELETE_PRODUCT_BY_ID_SUCCESS`,
    DELETE_PRODUCT_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/DELETE_PRODUCT_BY_ID_FAILURE`,

    CREATE_DUMMY_PROD: `${STATE_REDUCER_KEY}/CREATE_DUMMY_PROD`,
    CREATE_DUMMY_PROD_REQUEST: `${STATE_REDUCER_KEY}/CREATE_DUMMY_PROD_REQUEST`,
    CREATE_DUMMY_PROD_SUCCESS: `${STATE_REDUCER_KEY}/CREATE_DUMMY_PROD_SUCCESS`,
    CREATE_DUMMY_PROD_FAILURE: `${STATE_REDUCER_KEY}/CREATE_DUMMY_PROD_FAILURE`


};
